### ISSUE TITLE
make failure

### ISSUE THREAD

**Issue by nayansinghal** [my89/SituationCrf#1]
I am trying to run the system in TACC machine and while making caffe (cd build; cmake ..;) I am getting this error. 
***************** Caffe Configuration Summary *******************
-- General:
--   Version           :   1.0.0-rc3
--   Git               :   5d91f8a-dirty
--   System            :   Linux
--   C++ compiler      :   /usr/bin/c++
--   Release CXX flags :   -O3 -DNDEBUG -fPIC -Wall -Wno-sign-compare -Wno-uninitialized
--   Debug CXX flags   :   -g -fPIC -Wall -Wno-sign-compare -Wno-uninitialized
--   Build type        :   Release
-- 
--   BUILD_SHARED_LIBS :   ON
--   BUILD_python      :   ON
--   BUILD_matlab      :   OFF
--   BUILD_docs        :   ON
--   CPU_ONLY          :   OFF
--   USE_OPENCV        :   ON
--   USE_LEVELDB       :   ON
--   USE_LMDB          :   ON
--   ALLOW_LMDB_NOLOCK :   OFF
-- 
-- Dependencies:
--   BLAS              :   Yes (Atlas)
--   Boost             :   Yes (ver. 1.55)
--   glog              :   Yes
--   gflags            :   Yes
--   protobuf          :   Yes (ver. 2.5.0)
--   lmdb              :   Yes (ver. 0.9.70)
--   LevelDB           :   Yes (ver. 1.17)
--   Snappy            :   Yes (ver. 1.1.3)
--   OpenCV            :   Yes (ver. 3.1.0)
--   CUDA              :   Yes (ver. 7.0)
-- 
-- NVIDIA CUDA:
--   Target GPU(s)     :   Auto
--   GPU arch(s)       :   sm_35
--   cuDNN             :   Not found
-- 
-- Python:
--   Interpreter       :   /work/01932/dineshj/CS381V/caffe_install_scripts/anaconda/bin/python2.7 (ver. 2.7.11)
--   Libraries         :   /work/01932/dineshj/CS381V/caffe_install_scripts/anaconda/lib/libpython2.7.so (ver 2.7.11)
--   NumPy             :   /work/01932/dineshj/CS381V/caffe_install_scripts/anaconda/lib/python2.7/site-packages/numpy/core/include (ver 1.10.4)
-- 
-- Documentaion:
--   Doxygen           :   /usr/bin/doxygen (1.6.1)
--   config_file       :   /work/04393/nayans/SituationCrf/caffe/.Doxyfile
-- 
-- Install:
--   Install path      :   /work/04393/nayans/SituationCrf/caffe/build/install
-- 
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
Protobuf_LIBRARY

This is the log Error file. 
CMakeFiles/cmTC_b94ca.dir/CheckSymbolExists.c.o: In function `main':
CheckSymbolExists.c:(.text+0xc): undefined reference to `pthread_create'
collect2: ld returned 1 exit status
gmake[1]: *** [cmTC_b94ca] Error 1
gmake[1]: Leaving directory `/work/04393/nayans/SituationCrf/caffe/build/CMakeFiles/CMakeTmp'
gmake: *** [cmTC_b94ca/fast] Error 2

I have install htmlcxx-0.86 also but it didn't work. Someone please help me with it.

**Comment by my89** [comment]
Seem like you are missing protobufs. Follow the installation instructions from the caffe website for getting all the prereqs. 

http://caffe.berkeleyvision.org/installation.html

**Comment by nayansinghal** [comment]
I have installed protobuf but it's still giving me the same error.
