### ISSUE TITLE
Demo appears to be down

### ISSUE THREAD

**Issue by awadsb1** [my89/SituationCrf#5]
Hi, your demo at http://imsitu.org/demo/ appears to be down.  Clicking one of your sample images, or uploading one of my own gives:

Service Unavailable
The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.

Apache/2.4.7 (Ubuntu) Server at majestix.cs.washington.edu Port 80

**Comment by my89** [comment]
Awesome, thanks for letting me know. Its back online!

Mark
