### ISSUE TITLE
Prediction with Classification.bin fails

### ISSUE THREAD

**Issue by awadsb1** [my89/SituationCrf#6]
Is there a better way to predict on a single image?  Using Classification.bin and  "../of500_crf_1024/deploy.prototxt" fails at the CHECK statements in classification.cpp (only one input and output), and even after removing them, it fails later after the crf-log-loss layer is connected and then set up (line 148 on classification.cpp).

**Comment by my89** [comment]
Hi, 

Have you seen : https://github.com/my89/imSitu ? I've moved all the code over to pytorch and made it way more usable. It supports producing predictions/features of all images in a directory out of the box. It could be easily and obviously modified to do just one image.

**Comment by awadsb1** [comment]
No, I haven't seen this.  I'll take a look, thanks!
